services:
  django:
    build: .
    command: gunicorn config.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
    restart: always

  celery_worker:
    build: .
    command: celery -A config worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  celery_beat:
    build: .
    command: celery -A config beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env
    restart: always

  redis:
    image: redis:alpine
    restart: always

  # rs485_reader:
  #   image: python:3.10-slim
  #   volumes:
  #     - .:/app
  #   command: python /app/rs485_reader.py
  #   devices:
  #     - "/dev/serial0:/dev/serial0"  # Điều chỉnh nếu cần thiết cho cổng RS-485
  #   restart: always
