# Generated by Django 5.0.6 on 2024-08-28 03:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='customer/images/default.png', upload_to='customer/images/')),
            ],
        ),
        migrations.CreateModel(
            name='CapNhatDuLieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback', models.CharField(max_length=100)),
                ('tong', models.CharField(blank=True, max_length=20, null=True)),
                ('thong_bao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=264)),
                ('last_name', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('user_name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('image', models.ImageField(default='QRcodes/images/default.png', upload_to='QRcodes/images/')),
                ('time', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='QRcodes/images/default.png', upload_to='QRcodes/images')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThongKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('dia_chi', models.TextField(max_length=1000, null=True)),
                ('so_cccd', models.CharField(max_length=15, null=True)),
                ('ngay_sinh', models.CharField(max_length=25, null=True)),
                ('ticket_number', models.IntegerField(null=True)),
                ('feedback', models.CharField(max_length=10, null=True)),
                ('service', models.CharField(max_length=10, null=True)),
                ('ngay_quet', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ThongTinQR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_cccd', models.CharField(max_length=20)),
                ('so_cmnd_cu', models.CharField(max_length=20)),
                ('ho_va_ten', models.TextField(max_length=100)),
                ('ngay_sinh', models.CharField(max_length=20)),
                ('gioi_tinh', models.CharField(max_length=10)),
                ('dia_chi', models.TextField(max_length=2000)),
                ('ngay_cap', models.TextField(max_length=150)),
                ('so_cccd_2', models.CharField(max_length=20)),
                ('so_cmnd_cu_2', models.CharField(max_length=20)),
                ('ho_va_ten_2', models.TextField(max_length=100)),
                ('ngay_sinh_2', models.CharField(max_length=20)),
                ('gioi_tinh_2', models.CharField(max_length=10)),
                ('dia_chi_2', models.TextField(max_length=2000)),
                ('ngay_cap_2', models.TextField(max_length=150)),
                ('so_cccd_3', models.CharField(max_length=20)),
                ('so_cmnd_cu_3', models.CharField(max_length=20)),
                ('ho_va_ten_3', models.TextField(max_length=100)),
                ('ngay_sinh_3', models.CharField(max_length=20)),
                ('gioi_tinh_3', models.CharField(max_length=10)),
                ('dia_chi_3', models.TextField(max_length=2000)),
                ('ngay_cap_3', models.TextField(max_length=150)),
                ('ngay_quet', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='TrangThai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('dia_chi', models.TextField(max_length=1000, null=True)),
                ('so_cccd', models.CharField(max_length=15, null=True)),
                ('ngay_sinh', models.CharField(max_length=255, null=True)),
                ('gioi_tinh', models.CharField(max_length=10, null=True)),
                ('ngay_cap', models.TextField(max_length=150, null=True)),
                ('ticket_number', models.IntegerField(null=True)),
                ('is_calling', models.BooleanField(default=False)),
                ('is_called', models.BooleanField(default=False)),
                ('feedback', models.CharField(max_length=10, null=True)),
                ('service', models.CharField(max_length=10, null=True)),
                ('trang_thai', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.employee')),
            ],
        ),
        migrations.CreateModel(
            name='DanhSachCho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('ticket_number', models.IntegerField(null=True)),
                ('employee', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='danh_sach_cho', to='customer.khachhang')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='assigned_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.service'),
        ),
        migrations.CreateModel(
            name='DichVuTungQuay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_thu_tuc', models.CharField(max_length=255)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.service')),
            ],
        ),
    ]
