# Generated by Django 5.0.6 on 2024-10-03 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_service_prefix_alter_khachhang_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='ho_ten_cha',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='ho_ten_me',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
