# Generated by Django 5.0.6 on 2024-10-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_khachhang_ho_ten_cha_khachhang_ho_ten_me'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongke',
            name='feedback',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
