# Generated by Django 5.0.6 on 2024-10-07 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_alter_thongke_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thongke',
            name='service',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
