# Generated by Django 5.0.6 on 2024-10-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_thongke_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khachhang',
            name='employee',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
