# Generated by Django 5.0.6 on 2024-10-11 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0006_alter_khachhang_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='quay_so',
            field=models.IntegerField(null=True),
        ),
    ]
