# Generated by Django 5.0.6 on 2025-07-07 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_service_quay_so'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='is_hidden',
            field=models.BooleanField(default=True),
        ),
    ]
