# Generated by Django 5.0.6 on 2025-08-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_service_is_hidden'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='now_serving_ticket',
            field=models.IntegerField(blank=True, help_text='Số thứ tự hiện đang được phục vụ tại quầy này', null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='service_details',
            field=models.TextField(blank=True, help_text='Nhập mỗi dịch vụ 1 dòng'),
        ),
    ]
