# Generated by Django 5.0.6 on 2024-10-09 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voice_chatbot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedHost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
